name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Major
        id: major
        uses: ./
        with:
          version: v1.0.0
          type: major
      - name: Minor
        id: minor
        uses: ./
        with:
          version: v1.0.0
          type: minor
      - name: Patch
        id: patch
        uses: ./
        with:
          version: v1.0.0
          type: patch
      - name: Test major
        run: |
          [ "${{ steps.major.outputs.next_version }}" = "v2.0.0" ]
      - name: Test minor
        run: |
          [ "${{ steps.minor.outputs.next_version }}" = "v1.1.0" ]
      - name: Test patch
        run: |
          [ "${{ steps.patch.outputs.next_version }}" = "v1.0.1" ]
